# Generated by Django 5.2.5 on 2025-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('broker', models.CharField(choices=[('exness_mt5', 'Exness/MT5'), ('binance', 'Binance'), ('paper', 'Paper')], max_length=20)),
                ('account_ref', models.CharField(max_length=128)),
                ('creds', models.JSONField(default=dict)),
                ('base_ccy', models.CharField(default='USD', max_length=10)),
                ('leverage', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('broker', 'account_ref')},
            },
        ),
    ]
