# Generated by Django 5.2.5 on 2025-11-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_add_mt5_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccount',
            name='creds',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
