# Generated by Django 5.2.5 on 2025-11-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_alter_brokeraccount_creds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokeraccount',
            name='creds',
        ),
    ]
