# Generated by Django 5.2.5 on 2025-11-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0006_brokeraccount_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccount',
            name='broker',
            field=models.CharField(choices=[('exness_mt5', 'Exness/MT5'), ('binance', 'Binance'), ('paper', 'Paper'), ('fbs', 'FBS')], max_length=20),
        ),
    ]
