# Generated by Django 5.2.5 on 2025-12-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0012_add_mt5'),
    ]

    def set_default_connectors(apps, schema_editor):
        BrokerAccount = apps.get_model("brokers", "BrokerAccount")
        BrokerAccount.objects.filter(broker="paper").update(connector="paper")

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='adapter_config',
            field=models.JSONField(blank=True, default=dict, help_text='Optional extra credentials/settings required by the selected connector.'),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='connector',
            field=models.CharField(choices=[('mt5_local', 'MetaTrader 5 Desktop (local terminal)'), ('exness_web', 'Exness Web Terminal API'), ('ctrader_api', 'cTrader Open API'), ('paper', 'Paper Simulator')], default='mt5_local', help_text='Transport used to connect to this broker account.', max_length=32),
        ),
        migrations.RunPython(set_default_connectors, migrations.RunPython.noop),
    ]
