# Generated by Django 5.2.5 on 2025-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0013_brokeraccount_adapter_config_brokeraccount_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone for this broker account (e.g. Europe/London). Used for reporting timestamps.', max_length=64),
        ),
    ]
