# Generated by Django 5.2.5 on 2025-08-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='allowed_symbols',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bot',
            name='allowed_timeframes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bot',
            name='default_qty',
            field=models.DecimalField(decimal_places=8, default=0.1, max_digits=20),
        ),
    ]
