# Generated by Django 5.2.5 on 2025-08-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_allowed_symbols_bot_allowed_timeframes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='auto_trade',
            field=models.BooleanField(default=False),
        ),
    ]
