# Generated by Django 5.2.5 on 2025-08-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_auto_trade'),
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='broker_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='brokers.brokeraccount'),
        ),
    ]
