# Generated by Django 5.2.5 on 2025-11-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_bot_broker_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='engine_mode',
            field=models.CharField(choices=[('external', 'External signals (TradingView/Telegram)'), ('harami', 'Internal Harami engine')], default='external', help_text="How this bot receives trade signals: 'external' = TV/Telegram/webhook, 'harami' = internal Harami engine.", max_length=32),
        ),
    ]
