# Generated by Django 5.2.5 on 2025-11-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_bot_engine_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='kill_switch_enabled',
            field=models.BooleanField(default=True, help_text='If enabled, the risk kill-switch may close positions early when risk looks too high or the engine predicts high probability against us.'),
        ),
    ]
