# Generated by Django 5.2.5 on 2025-11-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_bot_kill_switch_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='risk_max_concurrent_positions',
            field=models.PositiveIntegerField(default=5, help_text='Max total open positions across all symbols for this bot.'),
        ),
        migrations.AddField(
            model_name='bot',
            name='risk_max_positions_per_symbol',
            field=models.PositiveIntegerField(default=1, help_text='Max open positions per symbol for this bot.'),
        ),
    ]
