# Generated by Django 5.2.5 on 2025-11-18 22:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_bot_risk_max_concurrent_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='kill_switch_max_unrealized_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Max unrealized loss (as fraction of notional) before kill switch closes the trade. Example: 0.0100 = 1%.', max_digits=5),
        ),
        migrations.AddField(
            model_name='bot',
            name='max_trades_per_day',
            field=models.PositiveIntegerField(default=0, help_text='Max new trades per day (0 = no limit).'),
        ),
        migrations.AddField(
            model_name='bot',
            name='trade_interval_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minimum minutes between new trades (0 = no limit).'),
        ),
    ]
