# Generated by Django 5.2.5 on 2025-11-19 00:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_bot_kill_switch_max_unrealized_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='enabled_strategies',
            field=models.JSONField(blank=True, default=list, help_text='List of engine strategy names this bot can use. Empty = allow all (harami_v1, engulfing_v1, sansen_sutsumi_liquidity, sanpe_tonkachi_fvg, ...).'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='kill_switch_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='kill_switch_max_unrealized_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('100.0'))]),
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_trades_per_day',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='bot',
            name='trade_interval_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
