# Generated by Django 5.2.5 on 2025-11-19 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_alter_bot_max_trades_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='max_trades_per_day',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200000)]),
        ),
    ]
