# Generated by Django 5.2.5 on 2025-11-20 00:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_alter_bot_max_trades_per_day'),
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='allowed_symbols',
            field=models.JSONField(blank=True, default=list, help_text="Optional list of MT5 symbols this bot is allowed to trade, e.g. ['EURUSDm', 'XAUUSDm']. Empty list = allow all symbols."),
        ),
        migrations.AlterField(
            model_name='bot',
            name='allowed_timeframes',
            field=models.JSONField(blank=True, default=list, help_text="Optional list of timeframes this bot is allowed to trade on, e.g. ['5m', '15m']. Empty list = allow all timeframes."),
        ),
        migrations.AlterField(
            model_name='bot',
            name='auto_trade',
            field=models.BooleanField(default=False, help_text="If enabled, decisions with action='open' will send live orders to MT5. If disabled, the bot only creates signals/decisions (paper mode)."),
        ),
        migrations.AlterField(
            model_name='bot',
            name='broker_account',
            field=models.ForeignKey(blank=True, help_text='The MT5 (or other broker) account this bot trades on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='brokers.brokeraccount'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this bot configuration was created.'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='default_qty',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.10'), help_text='Default lot size per trade before SL distance is considered. Adjust per symbol volatility (e.g. 0.10 for EURUSD, 0.02 for XAUUSD).', max_digits=20),
        ),
        migrations.AlterField(
            model_name='bot',
            name='default_timeframe',
            field=models.CharField(default='5m', help_text="Primary timeframe used when fetching candles for this bot (e.g. '5m', '15m').", max_length=10),
        ),
        migrations.AlterField(
            model_name='bot',
            name='enabled_strategies',
            field=models.JSONField(blank=True, default=list, help_text="Optional list of engine strategy names this bot can use, e.g. ['harami_v1', 'engulfing_v1', 'sansen_sutsumi_liquidity', 'sanpe_tonkachi_fvg']. Empty list = allow all registered strategies."),
        ),
        migrations.AlterField(
            model_name='bot',
            name='engine_mode',
            field=models.CharField(choices=[('external', 'External signals (TradingView/Telegram)'), ('harami', 'Internal engine (candlestick/SMC)')], default='external', help_text="How this bot receives trade ideas: 'external' = signals from TradingView/Telegram/webhooks, 'harami' = internal candlestick/SMC engine.", max_length=32),
        ),
        migrations.AlterField(
            model_name='bot',
            name='kill_switch_enabled',
            field=models.BooleanField(default=True, help_text='If enabled, background tasks monitor unrealized PnL for this bot and close its positions automatically when loss exceeds the configured percentage threshold.'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='kill_switch_max_unrealized_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.0'), help_text='Maximum allowed unrealized loss as a percentage (e.g. 5.00 = −5%). If floating loss reaches this level and kill switch is enabled, positions are closed.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('100.0'))]),
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_trades_per_day',
            field=models.PositiveIntegerField(default=10, help_text='Daily cap on filled trades for this bot. Once this number of trades is filled in a day, new trade decisions are ignored. Set to 0 to disable the daily cap.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200000)]),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(help_text="Human-readable name for this bot, e.g. 'EURUSD M5 – Reversal Bot'.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='risk_max_concurrent_positions',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of open positions this bot may hold across all symbols at the same time.'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='risk_max_positions_per_symbol',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of open positions this bot may hold per symbol (e.g. 1 = never stack multiple EURUSD trades).'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='stopped', help_text="High-level state of the bot. Only bots with status='active' are allowed to trade.", max_length=10),
        ),
        migrations.AlterField(
            model_name='bot',
            name='trade_interval_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minimum time gap (in minutes) between trades for this bot. If the last trade was more recent than this, new entries are ignored. Set to 0 to disable the spacing.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='bot',
            field=models.ForeignKey(help_text='Bot this configuration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='bots.bot'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='key',
            field=models.CharField(help_text="Configuration key name, e.g. 'decision_min_score' or 'sizing_per_symbol'.", max_length=64),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='locked',
            field=models.BooleanField(default=False, help_text='If True, this config should not be modified by automated tuning/sync jobs.'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='value',
            field=models.JSONField(default=dict, help_text='JSON value for this configuration key (structure depends on the key).'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='bot',
            field=models.ForeignKey(help_text='Bot that owns this strategy configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='bots.bot'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='enabled',
            field=models.BooleanField(default=True, help_text='If disabled, this strategy configuration is ignored for the bot.'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(help_text="Strategy name, e.g. 'harami_v1', 'engulfing_v1', or a custom label.", max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='params',
            field=models.JSONField(default=dict, help_text='JSON parameters for this strategy (risk, filters, etc.).'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='version',
            field=models.CharField(default='v1', help_text="Strategy version tag, e.g. 'v1', 'v2', 'experiment_01'.", max_length=32),
        ),
    ]
