# Generated by Django 5.2.5 on 2025-11-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_alter_bot_allowed_symbols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(help_text="Human-readable name for this bot, e.g. 'EURUSD M5 – Reversal Bot'.", max_length=100),
        ),
    ]
