# Generated by Django 5.2.5 on 2025-11-20 17:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_bot_owner_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='kill_switch_max_unrealized_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.0'), help_text='Maximum allowed unrealized loss as a percentage (e.g. 5.00 = 5%). If floating loss reaches this level and kill switch is enabled, positions are closed.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('100.0'))]),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(help_text="Human-readable name for this bot, e.g. 'EURUSD M5 Reversal Bot'.", max_length=100),
        ),
    ]
