# Generated by Django 5.2.5 on 2025-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0022_bot_allow_opposite_scalp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='enabled_strategies',
            field=models.JSONField(blank=True, default=list, help_text='Select which engine strategies this bot may run (tick one or more). Examples: harami_v1, engulfing_v1, engine_v2.'),
        ),
    ]
