# Generated by Django 5.2.5 on 2025-11-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0023_alter_bot_enabled_strategies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='enabled_strategies',
            field=models.JSONField(blank=True, default=list, help_text='Select which engine strategies this bot may run (tick one or more). Examples: Harami, Engulfing, Hammer, Marubozu, Shooting Star, Three Soldiers, Sanpe Tonkachi FVG, Sansen Sutsumi Liquidity, Doji, Price Action Pin Bar.'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(help_text="Strategy name, e.g. 'harami', 'engulfing', or a custom label.", max_length=100),
        ),
    ]
