# Generated by Django 5.2.5 on 2025-11-26 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0024_alter_bot_enabled_strategies_alter_strategy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='decision_min_score',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5'), help_text='Minimum decision score required for this bot (overrides global default).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='bot',
            name='enabled_strategies',
            field=models.JSONField(blank=True, default=list, help_text='Select which engine strategies this bot may run (tick one or more). Examples: Harami, Engulfing, Hammer, Marubozu, Shooting Star, Three Soldiers, Sanpe Tonkachi FVG, Sansen Sutsumi Liquidity, Doji, Price Action Pin Bar, Doji Breakout.'),
        ),
        migrations.DeleteModel(
            name='BotConfig',
        ),
    ]
