# Generated by Django 5.2.5 on 2025-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0026_alter_bot_engine_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='engine_mode',
            field=models.CharField(choices=[('external', 'External signals (TradingView/Telegram)'), ('harami', 'Internal engine (candlestick/SMC)')], default='harami', help_text="How this bot receives trade ideas: 'external' = signals from TradingView/Telegram/webhooks, 'harami' = internal candlestick/SMC engine.", max_length=32),
        ),
    ]
