# Generated by Django 5.2.5 on 2025-11-27 23:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0027_alter_bot_engine_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='default_sl_pips',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Default stop-loss distance for new decisions, expressed in pips.', max_digits=6),
        ),
        migrations.AddField(
            model_name='bot',
            name='default_tp_pips',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Default take-profit distance for new decisions, expressed in pips.', max_digits=6),
        ),
    ]
