# Generated by Django 5.2.5 on 2025-11-28 00:27

from django.db import migrations, models

import secrets
import string


def generate_id():
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(10))


def populate_ids(apps, schema_editor):
    Bot = apps.get_model("bots", "Bot")
    for bot in Bot.objects.filter(bot_id__isnull=True):
        bot.bot_id = generate_id()
        bot.save(update_fields=["bot_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0028_bot_default_sl_pips_bot_default_tp_pips'),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="bot_id",
            field=models.CharField(
                max_length=10,
                unique=True,
                null=True,
                blank=True,
                help_text="Immutable alphanumeric identifier for UI references.",
            ),
        ),
        migrations.RunPython(populate_ids, migrations.RunPython.noop),
    ]
