# Generated by Django 5.2.5 on 2025-11-28 14:28

import bots.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0029_bot_id_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='allowed_trading_days',
            field=models.JSONField(blank=True, default=bots.models.default_trading_days, help_text='Weekdays (mon..sun) during which the bot can open new trades.'),
        ),
        migrations.AddField(
            model_name='bot',
            name='trading_profile',
            field=models.CharField(choices=[('very_safe', 'Very Safe (Beginner)'), ('balanced', 'Balanced'), ('day_trader', 'Aggressive Day Trader'), ('scalper', 'Scalper'), ('long_term', 'Long-Term Investor'), ('custom', 'Custom / Advanced')], default='very_safe', help_text='Choose the profile/default behavior for this bot.', max_length=64),
        ),
        migrations.AddField(
            model_name='bot',
            name='trading_window_end',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Local time to stop opening trades each day.'),
        ),
        migrations.AddField(
            model_name='bot',
            name='trading_window_start',
            field=models.TimeField(default=datetime.time(6, 0), help_text='Local time to start opening trades each day.'),
        ),
    ]
