# Generated by Django 5.2.5 on 2025-11-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0030_asset_category'),
        ('bots', '0030_bot_allowed_trading_days_bot_trading_profile_and_more'),
    ]

    operations = [
    ]
