# Generated by Django 5.2.5 on 2025-12-03 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0034_bot_psychology_config'),
        ('execution', '0032_scalperprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='scalper_params',
            field=models.JSONField(blank=True, default=dict, help_text='Per-bot overrides for the scalper profile (symbols, sessions, risk). Keys mirror ScalperProfile.config – leave empty to inherit profile defaults.'),
        ),
        migrations.AddField(
            model_name='bot',
            name='scalper_profile',
            field=models.ForeignKey(blank=True, help_text="Optional scalper configuration profile. Required when engine_mode='scalper'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='execution.scalperprofile'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='engine_mode',
            field=models.CharField(choices=[('external', 'External signals (TradingView/Telegram)'), ('harami', 'Internal engine (candlestick/SMC)'), ('scalper', 'Internal scalper (M1-M5 high frequency)')], default='harami', help_text="How this bot receives trade ideas: 'external' = signals from TradingView/Telegram/webhooks, 'harami' = internal candlestick/SMC engine.", max_length=32),
        ),
    ]
