# Generated by Django 5.2.5 on 2025-12-05 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0036_update_scalper_min_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='decision_min_score',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5'), help_text='Minimum decision score required for this bot. Set to 0 to inherit the scalper profile/global default.', max_digits=6),
        ),
    ]
