# Generated by Django 5.2.5 on 2025-12-12 21:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0040_auto_allocation_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='allocation_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Loss limit expressed as a percent of the allocation. Defaults to 100%% (stop once the entire allocation is lost). Set to 0 to disable.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))]),
        ),
    ]
