# Generated by Django 5.2.5 on 2025-12-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0041_allocation_baseline'),
        ('bots', '0041_alter_bot_allocation_loss_pct'),
    ]

    operations = [
    ]
