# Generated by Django 5.2.5 on 2025-12-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0043_merge_auto_trade_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='enabled_strategies',
            field=models.JSONField(blank=True, default=list, help_text='Select which strategies this bot may run while auto-trade is disabled (tick one or more). Examples: Harami, Engulfing, Hammer, Marubozu, Shooting Star, Three Soldiers, Sanpe Tonkachi FVG, Sansen Sutsumi Liquidity, Doji, Price Action Pin Bar, Doji Breakout.'),
        ),
    ]
