# Generated by Django 5.2.5 on 2025-12-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0044_alter_bot_enabled_strategies'),
        ('bots', '0044_normalize_scalper_units'),
    ]

    operations = [
    ]
