# Generated by Django 5.2.5 on 2026-09-14 19:09

from django.db import migrations, models
import core.trading_schedule


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0050_bot_asset_recommended_config_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='trading_windows',
            field=models.JSONField(blank=True, default=list, help_text='Optional multiple windows with start, end, timezone and allowed_days; empty uses the single window.', validators=[core.trading_schedule.validate_trading_windows]),
        ),
    ]
