# Generated by Django 5.2.5 on 2026-09-23 14:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0056_bot_kill_switch_triggered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='allocation_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), help_text='Virtual bankroll for this bot in account currency. Risk-based sizing uses this amount capped by equity; zero uses account equity. Fixed lots are unchanged. When cumulative realized losses reach this allocation (or the configured loss %), trading pauses.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='bot',
            name='position_sizing_mode',
            field=models.CharField(choices=[('fixed', 'Fixed lot'), ('risk', 'Risk based')], default='risk', help_text='Use the fixed default lot or calculate volume from allocation (capped by equity), or equity when unallocated, and stop-loss risk.', max_length=12),
        ),
        migrations.AlterField(
            model_name='bot',
            name='risk_per_trade_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), help_text='Percentage of allocation capped by current account equity, or equity when allocation is zero, risked in risk-based mode.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
