# Generated by Django 5.2.5 on 2025-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_workerheartbeat"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(default="INFO", max_length=16)),
                ("component", models.CharField(max_length=64)),
                ("message", models.TextField()),
                ("task_name", models.CharField(blank=True, max_length=128)),
                ("task_id", models.CharField(blank=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-ts"],
                "indexes": [
                    models.Index(fields=["ts"], name="core_celery_ts_idx"),
                    models.Index(fields=["task_name", "ts"], name="core_celery_task_ts_idx"),
                ],
            },
        ),
    ]
