# Generated by Django 5.2.5 on 2025-11-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_celeryactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='celeryactivity',
            new_name='core_celery_ts_ae4e5e_idx',
            old_name='core_celery_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='celeryactivity',
            new_name='core_celery_task_na_1bdeb1_idx',
            old_name='core_celery_task_ts_idx',
        ),
    ]
