# Generated by Django 5.2.5 on 2025-12-05 15:15

from django.db import migrations


def purge_logs(apps, schema_editor):
    Audit = apps.get_model("core", "Audit")
    CeleryActivity = apps.get_model("core", "CeleryActivity")
    Audit.objects.all().delete()
    CeleryActivity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_celery_ts_idx_core_celery_ts_ae4e5e_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(purge_logs, purge_logs),
    ]
