# Generated by Django 5.2.5 on 2025-12-05 12:33

from datetime import timedelta
from decimal import Decimal

from django.db import migrations
from django.utils import timezone


def seed_default_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscription", "SubscriptionPlan")
    UserSubscription = apps.get_model("subscription", "UserSubscription")
    User = apps.get_model("auth", "User")

    # Only seed demo data when the table is empty to avoid touching real plans.
    if SubscriptionPlan.objects.exists():
        return

    plan_specs = [
        {
            "name": "Starter",
            "broker_accounts_limit": 1,
            "bots_limit": 1,
            "duration_days": 30,
            "price": Decimal("149.00"),
            "description": "Entry plan for single-account traders exploring EzTrade.",
        },
        {
            "name": "Pro",
            "broker_accounts_limit": 3,
            "bots_limit": 5,
            "duration_days": 30,
            "price": Decimal("349.00"),
            "description": "Adds additional bots plus multiple broker accounts for scaling teams.",
        },
        {
            "name": "Institutional",
            "broker_accounts_limit": 10,
            "bots_limit": 12,
            "duration_days": 90,
            "price": Decimal("799.00"),
            "description": "High-cap allocation for desks managing several strategies concurrently.",
        },
    ]

    created_plans = [
        SubscriptionPlan.objects.create(**spec) for spec in plan_specs
    ]

    admin_user = User.objects.filter(is_superuser=True).order_by("id").first()
    if not admin_user or not created_plans:
        return

    starter_plan = created_plans[0]
    expires_at = timezone.now() + timedelta(days=starter_plan.duration_days or 30)

    UserSubscription.objects.create(
        user=admin_user,
        plan=starter_plan,
        is_active=True,
        expires_at=expires_at,
    )


def unseed_default_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscription", "SubscriptionPlan")
    UserSubscription = apps.get_model("subscription", "UserSubscription")

    plan_names = ["Starter", "Pro", "Institutional"]
    plans = list(SubscriptionPlan.objects.filter(name__in=plan_names))

    if not plans:
        return

    UserSubscription.objects.filter(plan__in=plans).delete()
    SubscriptionPlan.objects.filter(id__in=[plan.id for plan in plans]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(seed_default_plans, unseed_default_plans),
    ]
