# Generated by Django 5.2.5 on 2025-08-12 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('proportional', 'Proportional'), ('fixed', 'Fixed Size'), ('equity_pct', 'Equity Percent')], default='proportional', max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('min_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='brokers.brokeraccount')),
                ('master_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='bots.bot')),
            ],
            options={
                'unique_together': {('master_bot', 'broker_account')},
            },
        ),
    ]
