# Generated by Django 5.2.5 on 2025-08-11 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_id', models.CharField(max_length=64, unique=True)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('ack', 'ack'), ('filled', 'filled'), ('part_filled', 'part_filled'), ('canceled', 'canceled'), ('error', 'error')], default='new', max_length=12)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bots.bot')),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='brokers.brokeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('exec_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='execution.order')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(default='5m', max_length=10)),
                ('direction', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=5)),
                ('payload', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(db_index=True, max_length=128)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dedupe_key'], name='execution_s_dedupe__fcca02_idx')],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'open'), ('close', 'close'), ('ignore', 'ignore')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('params', models.JSONField(default=dict)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='bots.bot')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='execution.signal')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('qty', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('sl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='brokers.brokeraccount')),
            ],
            options={
                'unique_together': {('broker_account', 'symbol')},
            },
        ),
    ]
