# Generated by Django 5.2.5 on 2025-08-11 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='bots.bot'),
        ),
    ]
