# Generated by Django 5.2.5 on 2025-08-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_allowed_symbols_bot_allowed_timeframes_and_more'),
        ('execution', '0002_alter_decision_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='bots.bot'),
        ),
    ]
