# Generated by Django 5.2.5 on 2025-08-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('execution', '0003_signal_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='trail_distance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='signal',
            name='trail_trigger',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PnLDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('realized', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unrealized', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_daily', to='brokers.brokeraccount')),
            ],
            options={
                'unique_together': {('broker_account', 'date')},
            },
        ),
    ]
