# Generated by Django 5.2.5 on 2025-08-13 01:10

from django.db import migrations, models
from django.db.models import Min

def squash_dupes(apps, schema_editor):
    Signal = apps.get_model("execution", "Signal")
    # keep earliest row per dedupe_key; delete the rest
    rows = (Signal.objects.values("dedupe_key")
            .annotate(keep_id=Min("id")))
    keep_ids = {r["keep_id"] for r in rows}
    Signal.objects.exclude(id__in=keep_ids).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("execution", "<PUT-YOUR-LAST-MIGRATION-NAME-HERE>"),
    ]
    operations = [
        migrations.RunPython(squash_dupes, migrations.RunPython.noop),
    ]



class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_signal_trail_distance_signal_trail_trigger_pnldaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='dedupe_key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
