# Generated by Django 5.2.5 on 2025-08-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_squash_signal_dupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('submitted', 'submitted'), ('filled', 'filled'), ('partially_filled', 'partially_filled'), ('closed', 'closed'), ('canceled', 'canceled'), ('error', 'error')], default='new', max_length=50),
        ),
    ]
