# Generated by Django 5.2.5 on 2025-11-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Account balance immediately after this execution.', max_digits=20, null=True),
        ),
    ]
