# Generated by Django 5.2.5 on 2025-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_execution_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('ack', 'ack'), ('filled', 'filled'), ('part_filled', 'part_filled'), ('canceled', 'canceled'), ('error', 'error')], default='new', max_length=50),
        ),
    ]
