# Generated by Django 5.2.5 on 2025-11-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0020_tradelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tradelog',
            new_name='execution_t_symbol_2a18cf_idx',
            old_name='execution_t_symbol_673a49_idx',
        ),
    ]
