# Generated by Django 5.2.5 on 2025-11-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0021_indexes'),
        ('execution', '0021_rename_execution_t_symbol_673a49_idx_execution_t_symbol_2a18cf_idx'),
    ]

    operations = [
    ]
