# Generated by Django 5.2.5 on 2025-11-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0022_merge_20251121_1801'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='decision',
            name='decision_bot_decided_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='position_status_broker_symbol_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signal_symbol_received_idx',
        ),
    ]
