# Generated by Django 5.2.5 on 2025-11-25 19:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0025_executionsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionsetting',
            name='decision_allow_hedging',
            field=models.BooleanField(default=False, help_text='Allow hedged (both-direction) exposure when evaluating new decisions and broker dispatch.'),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='decision_flip_cooldown_min',
            field=models.PositiveIntegerField(default=15, help_text='Minutes to wait after a flip before another flip_close can be created for the same bot/symbol.'),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='decision_flip_score',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.8'), help_text='Score threshold to flip an existing position instead of blocking opposite entries.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='decision_max_flips_per_day',
            field=models.PositiveIntegerField(default=3, help_text='Daily cap on flip_close actions per bot/symbol (0 = no cap).'),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='decision_min_score',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.5'), help_text='Default minimum score required for opens when a bot has no per-symbol override.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='decision_order_cooldown_sec',
            field=models.PositiveIntegerField(default=60, help_text='Minimum seconds between new open orders per bot/symbol (max of this and timeframe-derived gap).'),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='decision_scalp_qty_multiplier',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.3'), help_text='Quantity multiplier applied to opposite scalp orders (relative to bot default qty).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='decision_scalp_sl_offset',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0003'), help_text='SL offset (price units) for opposite scalp trades when stacking is allowed.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='decision_scalp_tp_offset',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0005'), help_text='TP offset (price units) for opposite scalp trades when stacking is allowed.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='early_exit_max_unrealized_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.02'), help_text='Kill positions when unrealized loss exceeds this fraction of notional (monitor task).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='mt5_default_contract_size',
            field=models.PositiveIntegerField(default=100000, help_text='Fallback contract size for notional checks when MT5 symbol_info is unavailable.'),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='order_ack_timeout_seconds',
            field=models.PositiveIntegerField(default=180, help_text='Auto-cancel orders stuck in new/ack older than this many seconds.'),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='paper_start_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Displayed balance/equity for paper broker accounts.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='trailing_distance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0003'), help_text='Distance (price units) to trail behind peak once trigger hit (ATR-adjusted if provided).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='trailing_trigger',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0005'), help_text='Profit trigger (price units) before trailing stops start.', max_digits=10),
        ),
    ]
