# Generated by Django 5.2.5 on 2025-11-28 00:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0027_merge_20251125_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionsetting',
            name='bot_min_default_qty',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.01'), help_text='Global minimum lot size enforced for bot default qty selections.', max_digits=20),
        ),
    ]
