# Generated by Django 5.2.5 on 2025-11-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0029_tradingprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingprofile',
            options={'ordering': ['slug']},
        ),
    ]
