# Generated by Django 5.2.5 on 2025-12-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0031_executionsetting_psychology_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScalperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
