# Generated by Django 5.2.5 on 2025-12-04 15:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0032_scalperprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionsetting',
            name='max_slippage_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Maximum allowed slippage (in points) for scalper trades. 0 = disabled.', max_digits=8),
        ),
        migrations.AddField(
            model_name='executionsetting',
            name='max_spread_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), help_text='Maximum allowed spread (in points) for scalper trades. 0 = disabled.', max_digits=8),
        ),
    ]
