# Generated by Django 5.2.5 on 2025-12-04 16:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0033_add_scalper_guardrails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionsetting',
            name='max_order_notional',
            field=models.DecimalField(decimal_places=2, default=Decimal('20000'), help_text='Maximum notional (account currency) per order; set 0 to disable.', max_digits=20),
        ),
    ]
