# Generated by Django 5.2.5 on 2025-12-04 16:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0034_increase_max_notional_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionsetting',
            name='max_order_lot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.20'), help_text='Maximum lot size per order; set 0 to disable.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='executionsetting',
            name='max_order_notional',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), help_text='Maximum notional (account currency) per order; set 0 to disable.', max_digits=20),
        ),
    ]
