# Generated by Django 5.2.5 on 2025-12-04 17:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0035_bump_order_caps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionsetting',
            name='max_slippage_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='Maximum allowed slippage (in points) for scalper trades. 0 = disabled.', max_digits=8),
        ),
    ]
