# Generated by Django 5.2.5 on 2025-12-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0037_scalperrunlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scalperrunlog',
            new_name='execution_s_bot_id_ea73d5_idx',
            old_name='execution_sc_bot_crea_7c01f6_idx',
        ),
        migrations.RenameIndex(
            model_name='scalperrunlog',
            new_name='execution_s_session_fb04ec_idx',
            old_name='execution_sc_session_c0c5c7_idx',
        ),
    ]
