# Generated by Django 5.2.5 on 2025-12-05 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0035_bot_scalper_params_bot_scalper_profile_and_more'),
        ('brokers', '0012_add_mt5'),
        ('execution', '0038_rename_execution_sc_bot_crea_7c01f6_idx_execution_s_bot_id_ea73d5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('symbol', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='bots.bot')),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='brokers.brokeraccount')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='execution.decision')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='execution.order')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='execution.position')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='execution.signal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='execution_j_created_69f81d_idx'), models.Index(fields=['event_type', 'created_at'], name='execution_j_event_t_65a9cb_idx'), models.Index(fields=['bot', 'created_at'], name='execution_j_bot_id_eacb2f_idx'), models.Index(fields=['broker_account', 'created_at'], name='execution_j_broker__7944a4_idx')],
            },
        ),
    ]
