# Generated by Django 5.2.5 on 2025-12-05 14:16

from django.db import migrations


BTC_SYMBOL_CONFIG = {
    "aliases": ["BTCUSDm"],
    "execution_timeframes": ["M1"],
    "context_timeframes": ["M5", "M15", "H1"],
    "sl_points": {"min": 200, "max": 600},
    "tp_r_multiple": 1.3,
    "be_trigger_r": 1.0,
    "be_buffer_r": 0.25,
    "trail_trigger_r": 1.8,
    "trail_mode": "structure",
    "max_spread_points": 120,
    "max_slippage_points": 60,
    "allow_countertrend": False,
    "risk_pct": 0.35,
}


def add_btc_symbol(apps, schema_editor):
    ScalperProfile = apps.get_model("execution", "ScalperProfile")
    for profile in ScalperProfile.objects.all():
        config = profile.config or {}
        symbols = config.setdefault("symbols", {})
        if "BTCUSD" in symbols:
            continue
        symbols["BTCUSD"] = BTC_SYMBOL_CONFIG
        profile.config = config
        profile.save(update_fields=["config", "updated_at"])


def remove_btc_symbol(apps, schema_editor):
    ScalperProfile = apps.get_model("execution", "ScalperProfile")
    for profile in ScalperProfile.objects.all():
        config = profile.config or {}
        symbols = config.get("symbols") or {}
        if "BTCUSD" in symbols:
            symbols.pop("BTCUSD", None)
            profile.config = config
            profile.save(update_fields=["config", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0039_journalentry'),
    ]

    operations = [
        migrations.RunPython(add_btc_symbol, remove_btc_symbol),
    ]
