# Generated by Django 5.2.5 on 2025-12-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0040_add_btc_scalper_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
