# Generated by Django 5.2.5 on 2025-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0042_prune_celery_journal_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='broker_ticket',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='broker_ticket',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
