# Generated by Django 5.2.5 on 2025-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0043_order_broker_ticket_tradelog_broker_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='closed_at_broker',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='opened_at_broker',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
