# Generated by Django 5.1.3 on 2026-08-26 01:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0045_merge_20251217_0520'),
        ('brokers', '0014_brokeraccount_timezone'),
        ('execution', '0045_scalper_exit_policy_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('free_margin', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('margin_level', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('currency', models.CharField(blank=True, default='', max_length=12)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_position_ticket', models.BigIntegerField()),
                ('ownership', models.CharField(choices=[('ez_trade', 'EZ Trade'), ('manual', 'Manual'), ('external', 'External/unknown')], default='external', max_length=16)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('profit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('swap', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('magic', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('strategy_name', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('missing', 'missing')], default='open', max_length=12)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('broker_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['broker_account_id', 'broker_position_ticket'],
            },
        ),
        migrations.CreateModel(
            name='BrokerSymbolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_symbol', models.CharField(max_length=16)),
                ('broker_symbol', models.CharField(blank=True, default='', max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('last_candle_at', models.DateTimeField(blank=True, null=True)),
                ('last_resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['canonical_symbol'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('prepared', 'prepared'), ('submitting', 'submitting'), ('ambiguous', 'ambiguous'), ('reconciled', 'reconciled'), ('accepted', 'accepted'), ('partial', 'partial'), ('rejected', 'rejected'), ('failed', 'failed')], default='prepared', max_length=16)),
                ('request_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('broker_order_ticket', models.BigIntegerField(blank=True, null=True)),
                ('broker_deal_ticket', models.BigIntegerField(blank=True, null=True)),
                ('broker_position_ticket', models.BigIntegerField(blank=True, null=True)),
                ('mt5_retcode', models.BigIntegerField(blank=True, null=True)),
                ('mt5_retcode_description', models.CharField(blank=True, default='', max_length=255)),
                ('requested_qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filled_qty', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('remaining_qty', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('actual_fill_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order_id', 'attempt_no'],
            },
        ),
        migrations.CreateModel(
            name='RiskPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6)),
                ('max_daily_loss_pct', models.DecimalField(decimal_places=3, default=Decimal('1.5'), max_digits=6)),
                ('max_account_drawdown_pct', models.DecimalField(decimal_places=3, default=Decimal('5.0'), max_digits=6)),
                ('max_positions', models.PositiveIntegerField(default=1)),
                ('max_positions_per_symbol', models.PositiveIntegerField(default=1)),
                ('max_entry_trades_per_day', models.PositiveIntegerField(default=3)),
                ('max_lot', models.DecimalField(decimal_places=8, default=Decimal('0.05'), max_digits=12)),
                ('max_spread_points', models.DecimalField(decimal_places=4, default=Decimal('30'), max_digits=12)),
                ('deviation_points', models.PositiveIntegerField(default=8)),
                ('stop_after_daily_profit_pct', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('entries_enabled', models.BooleanField(default=False)),
                ('emergency_stop', models.BooleanField(default=False)),
                ('emergency_close_owned_positions', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='execution',
            name='broker_deal_ticket',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='broker_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='execution',
            name='broker_order_ticket',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='broker_position_ticket',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='commission',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='execution',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='swap',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='actual_fill_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='broker_deal_ticket',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='broker_order_ticket',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='broker_position_ticket',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='broker_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='filled_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='intent',
            field=models.CharField(choices=[('entry', 'entry'), ('exit', 'exit'), ('modify', 'modify protection')], default='entry', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='mt5_retcode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mt5_retcode_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('ack', 'ack'), ('filled', 'filled'), ('part_filled', 'part_filled'), ('canceled', 'canceled'), ('rejected', 'rejected'), ('error', 'error')], default='new', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.UniqueConstraint(fields=('order', 'broker_deal_ticket'), name='execution_unique_order_deal_ticket'),
        ),
        migrations.AddField(
            model_name='accountsnapshot',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_snapshots', to='brokers.brokeraccount'),
        ),
        migrations.AddField(
            model_name='brokerposition',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_positions', to='bots.bot'),
        ),
        migrations.AddField(
            model_name='brokerposition',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_positions', to='brokers.brokeraccount'),
        ),
        migrations.AddField(
            model_name='brokerposition',
            name='originating_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_positions', to='execution.order'),
        ),
        migrations.AddField(
            model_name='brokerposition',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_positions_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokersymbolmapping',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_mappings', to='brokers.brokeraccount'),
        ),
        migrations.AddField(
            model_name='executionattempt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='execution.order'),
        ),
        migrations.AddField(
            model_name='riskpolicy',
            name='broker_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_policy', to='brokers.brokeraccount'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['broker_account', 'captured_at'], name='execution_a_broker__af70a9_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerposition',
            index=models.Index(fields=['broker_account', 'status', 'symbol'], name='execution_b_broker__220e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerposition',
            index=models.Index(fields=['ownership', 'status'], name='execution_b_ownersh_6bf50a_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokerposition',
            constraint=models.UniqueConstraint(fields=('broker_account', 'broker_position_ticket'), name='execution_unique_broker_position_ticket'),
        ),
        migrations.AddConstraint(
            model_name='brokersymbolmapping',
            constraint=models.UniqueConstraint(fields=('broker_account', 'canonical_symbol'), name='execution_unique_account_canonical_symbol'),
        ),
        migrations.AddConstraint(
            model_name='executionattempt',
            constraint=models.UniqueConstraint(fields=('order', 'attempt_no'), name='execution_unique_attempt_no'),
        ),
    ]
