# Generated by Django 5.1.3 on 2026-08-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0046_accountsnapshot_brokerposition_brokersymbolmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskpolicy',
            name='live_trading_confirmed',
            field=models.BooleanField(default=False, help_text='Explicit operator confirmation required when MT5 reports a live-money account.'),
        ),
    ]
