# Generated by Django 5.1.3 on 2026-08-26 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0014_brokeraccount_timezone'),
        ('execution', '0047_riskpolicy_live_trading_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokersymbolmapping',
            name='ask',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='brokersymbolmapping',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='brokersymbolmapping',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brokersymbolmapping',
            name='spread',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='brokersymbolmapping',
            name='trading_status',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.CreateModel(
            name='MT5ConnectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=False)),
                ('active_login', models.CharField(blank=True, default='', max_length=64)),
                ('active_server', models.CharField(blank=True, default='', max_length=128)),
                ('company', models.CharField(blank=True, default='', max_length=128)),
                ('currency', models.CharField(blank=True, default='', max_length=12)),
                ('leverage', models.PositiveIntegerField(default=0)),
                ('account_mode', models.CharField(default='unknown', max_length=16)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('broker_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_connection_state', to='brokers.brokeraccount')),
            ],
        ),
    ]
