# Generated by Django 5.1.3 on 2026-08-26 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0048_brokersymbolmapping_ask_brokersymbolmapping_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='execution.decision'),
        ),
    ]
