# Generated by Django 5.1.3 on 2026-09-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0014_brokeraccount_timezone"),
        ("execution", "0050_risk_high_water_and_trailing_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountRiskDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_date", models.DateField()),
                (
                    "starting_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "starting_equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "high_equity",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("first_snapshot_at", models.DateTimeField(blank=True, null=True)),
                (
                    "baseline_source",
                    models.CharField(
                        choices=[
                            ("opening_snapshot", "Opening snapshot"),
                            ("mt5_history", "MT5 history reconstruction"),
                            ("demo_first_snapshot", "Demo first snapshot"),
                            ("manual", "Operator supplied"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="unavailable",
                        max_length=32,
                    ),
                ),
                ("baseline_locked", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broker_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_days",
                        to="brokers.brokeraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_date", "broker_account_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("broker_account", "risk_date"),
                        name="execution_unique_account_risk_day",
                    )
                ],
            },
        ),
    ]
