# Generated by Django 5.1.3 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0051_accountriskday"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="evaluation_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When strategy/decision evaluation began for latency telemetry.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="broker_response_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="execution_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="execution_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="mt5_worker_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_send_called_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="risk_validation_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
