# Generated by Django 5.2.5 on 2026-09-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0061_performance_history_baselines'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskpolicy',
            name='emergency_stop_triggered_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
