# Generated by Django 5.1.3 on 2026-10-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0063_brokerposition_cleared_from_positions_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerposition',
            name='loss_streak_accounted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='trade_pnl',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
