# Generated by Django 5.1.3 on 2026-10-01 16:44

from django.db import migrations, models
from django.db.models import Exists, OuterRef
from django.utils import timezone


def protect_legacy_outcomes(apps, schema_editor):
    alias = schema_editor.connection.alias
    broker_positions = apps.get_model("execution", "BrokerPosition").objects.using(alias)
    executions = apps.get_model("execution", "Execution").objects.using(alias)
    paper_positions = apps.get_model("execution", "Position").objects.using(alias)
    exit_fills = executions.filter(
        order__broker_account_id=OuterRef("broker_account_id"),
        broker_position_ticket=OuterRef("broker_position_ticket"),
        order__intent="exit",
    )
    accounted_at = timezone.now()
    # Pre-fix exit fragments may already have advanced the bot's streak. Leave
    # those positions out of the new position-level counter, including open
    # positions with partial exits. Preserve markers written since 0064.
    unaccounted = broker_positions.filter(loss_streak_accounted_at__isnull=True)
    unaccounted.filter(status="closed").update(loss_streak_accounted_at=accounted_at)
    unaccounted.exclude(status="closed").filter(Exists(exit_fills)).update(
        loss_streak_accounted_at=accounted_at,
    )
    # No reliable cycle PnL exists for paper positions spanning the upgrade.
    # New entry fills initialize this field to zero in record_fill.
    paper_positions.update(trade_pnl=None)


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0064_brokerposition_loss_streak_accounted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='trade_pnl',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.RunPython(protect_legacy_outcomes, migrations.RunPython.noop),
    ]
