# Generated by Django 5.2.5 on 2025-11-21 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('extra_emails', models.JSONField(blank=True, default=list)),
                ('notify_order_filled', models.BooleanField(default=True)),
                ('notify_order_error', models.BooleanField(default=True)),
                ('notify_order_canceled', models.BooleanField(default=False)),
                ('notify_daily_digest', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('15m', 'Every 15 minutes'), ('30m', 'Every 30 minutes'), ('1h', 'Every hour'), ('4h', 'Every 4 hours'), ('1d', 'Daily')], default='1d', max_length=3)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('skipped', 'skipped'), ('failed', 'failed')], default='sent', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='notificatio_user_id_83552f_idx')],
            },
        ),
    ]
